# Generated by Django 5.0.6 on 2024-06-25 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Menu',
        ),
    ]
